name: build docker image
on:
  push:
    branches:
      - release
  release:
    types: [created]
  workflow_dispatch: # 添加 workflow_dispatch 事件
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'info'
        type: choice
        options:
          - info
          - debug
      environment:
        description: 'Environment to deploy to'
        default: 'production'
        type: environment
        required: true
      dockerTag:
        description: "docker tag"
        required: false
        default: ${{ github.ref_name }}


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print GitHub context
        run: |
          echo "repository: ${{ github.repository }}"
          echo "actor: ${{ github.actor }}"
          echo "ref_name: ${{ github.ref_name }}"
          echo "logLevel: ${{ github.event.inputs.logLevel }}"
          echo "environment: ${{ github.event.inputs.environment }}"
          echo "dockerTag: ${{ github.event.inputs.dockerTag }}"
          
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Login to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }} 

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            shine1223/iycms:${{ github.event.inputs.dockerTag  }}
            shine1223/iycms:latest
            ghcr.io/shineTripodcat/iycms:${{ github.event.inputs.dockerTag  }}
            ghcr.io/shineTripodcat/iycms:latest
